name: "phlag"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PHLAG_APP_IMAGE:-phlag-app:latest}
    command:
      - /usr/local/bin/php
      - -S
      - 0.0.0.0:80
      - -t
      - public
      - public/index.php
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      APP_ENV: ${APP_ENV:-local}
    ports:
      - "80:80"
    volumes:
      - ./:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:80/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - phlag

  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-phlag}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - phlag

  redis:
    image: redis:8
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - phlag

volumes:
  pgdata:

networks:
  phlag:
    driver: bridge
